### ISSUE TITLE
Desfire Ev1

### ISSUE THREAD

**Issue by isaacl1107** [JPG-Consulting/rfid-desfire#2]
Hello - I've been trying  to use your library to try to read just the UID of a desfire EV1 card. I have several Classic cards that the rfc522 library can detect and read, but when I hold up the desfire EV1 card, nothing is displayed. Scanning the card with my phone displays the following information. Again I know reading application information requires des decryption, etc, but I just want to read the UID - is there a way to force the rfc522 to just dump all cards it sees?

** TagInfo scan (version 4.21.171) 2017-03-14 17:27:13 **
Report Type: External

-- INFO ------------------------------

# IC manufacturer:
NXP Semiconductors

# IC type:
MIFARE DESFire EV1

# DESFire Applications:

-- NDEF ------------------------------

# No NFC data set storage:

-- EXTRA ------------------------------

# Memory information:
Size: 512 bytes
Available: 320 bytes

# IC detailed information:
Capacitance: 70 pF

# Version information:
Vendor ID: NXP
Hardware info:
* Type/subtype: 0x01/0x02
* Version: 1.0
* Storage size: 512 bytes
* Protocol: ISO/IEC 14443-2 and -3
Software info:
* Type/subtype: 0x01/0x01
* Version: 1.5
* Storage size: 512 bytes
* Protocol: ISO/IEC 14443-3 and -4
Batch no: 0xBA6415C540
Production date: week 05, 2015

-- TECH ------------------------------

# Technologies supported:
ISO/IEC 7816-4 compatible
Native DESFire APDU framing
ISO/IEC 14443-4 (Type A) compatible
ISO/IEC 14443-3 (Type A) compatible
ISO/IEC 14443-2 (Type A) compatible

# Detailed protocol information:
ID: 04:xx:xx:xx:xx:xx:xx
ATQA: 0x4403
SAK: 0x20
ATS: 0x1C

**Comment by MadDogMayCry0** [comment]
Wich board u have? If 3$ aliwxpress board (rc522) then u have to change inductors (L1, L2) to 2.2Uh w 200mA or more (feel free w 1A :)) currency! Those one in china board has just 7mA currency, and Antenna has not enouth power to read DESFire or Ultralight C cards.

**Comment by Al-Ko-G8** [comment]
I was able to work with DESFire EV1 cards using $22 NFC card: 
https://www.amazon.com/gp/product/B00E0ODLWQ/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
and cheap Leonardo version: https://www.ebay.com/itm/400988209614

And yes, I have to modify this library. In any case, thank you so much, Stasikiii, it helped a lot.

**Comment by camr0** [comment]
Did anyone find a solution to this problem?

**Comment by isaacl1107** [comment]
> Did anyone find a solution to this problem?

Yes - I ended up buying the following like @Al-Ko-G8  suggested https://www.amazon.com/gp/product/B00E0ODLWQ/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
